export const data = [
  {
    key: '1',
    name: 'John',
    lastName: 'Doe',
    age: 28,
    userRole: 'Developer',
    email: 'john.doe@example.com',
    office: 'New York',
  },
  {
    key: '2',
    name: 'Jane',
    lastName: 'Smith',
    age: 34,
    userRole: 'Project Manager',
    email: 'jane.smith@example.com',
    office: 'Los Angeles',
  },
  {
    key: '3',
    name: 'Michael',
    lastName: 'Johnson',
    age: 45,
    userRole: 'Designer',
    email: 'michael.johnson@example.com',
    office: 'Chicago',
  },
  {
    key: '4',
    name: 'Emily',
    lastName: 'Davis',
    age: 29,
    userRole: 'QA Engineer',
    email: 'emily.davis@example.com',
    office: 'San Francisco',
  },
  {
    key: '5',
    name: 'David',
    lastName: 'Wilson',
    age: 38,
    userRole: 'System Administrator',
    email: 'david.wilson@example.com',
    office: 'Austin',
  },
  {
    key: '6',
    name: 'Sarah',
    lastName: 'Brown',
    age: 31,
    userRole: 'Data Analyst',
    email: 'sarah.brown@example.com',
    office: 'Seattle',
  },
];
